spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/train
    username: username
    password: password

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080
server:
  port: 8081
debug: true
